"""
VesselOptima — Phase 13: Backtesting & Decision Replay Reason Codes & Enums
"""

from enum import Enum


class BacktestRunStatus(str, Enum):
    CREATED = "CREATED"
    VALIDATING = "VALIDATING"
    READY = "READY"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class BacktestMode(str, Enum):
    DECISION_REPLAY = "DECISION_REPLAY"
    OUTCOME_BACKTEST = "OUTCOME_BACKTEST"
    BENCHMARK_BACKTEST = "BENCHMARK_BACKTEST"


class DecisionFrequency(str, Enum):
    EVENT_DRIVEN = "EVENT_DRIVEN"
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    CUSTOM = "CUSTOM"


class FailureReason(str, Enum):
    LOOKAHEAD_BIAS_DETECTED = "LOOKAHEAD_BIAS_DETECTED"
    MISSING_HISTORICAL_DATA = "MISSING_HISTORICAL_DATA"
    POINT_IN_TIME_UNCERTAIN = "POINT_IN_TIME_UNCERTAIN"
    INVALID_DATASET_VERSION = "INVALID_DATASET_VERSION"
    INCOMPLETE_OUTCOME = "INCOMPLETE_OUTCOME"
    PHASE_EXECUTION_FAILED = "PHASE_EXECUTION_FAILED"
    NON_DETERMINISTIC_RESULT = "NON_DETERMINISTIC_RESULT"
    CURRENCY_INCOMPATIBLE = "CURRENCY_INCOMPATIBLE"


class LeakageCode(str, Enum):
    LOOKAHEAD_BIAS_DETECTED = "LOOKAHEAD_BIAS_DETECTED"
    FUTURE_DATA_USED = "FUTURE_DATA_USED"
    POINT_IN_TIME_UNCERTAIN = "POINT_IN_TIME_UNCERTAIN"
    CURRENT_DATASET_USED = "CURRENT_DATASET_USED"
    FUTURE_DATASET_VERSION_USED = "FUTURE_DATASET_VERSION_USED"


class BenchmarkStrategyType(str, Enum):
    NO_ACTION = "NO_ACTION"
    CONTINUE_CURRENT_EMPLOYMENT = "CONTINUE_CURRENT_EMPLOYMENT"
    FIRST_FEASIBLE = "FIRST_FEASIBLE"
    BEST_EXPECTED_CONTRIBUTION = "BEST_EXPECTED_CONTRIBUTION"
    HISTORICAL_ACTUAL = "HISTORICAL_ACTUAL"


class HistoricalEventType(str, Enum):
    VESSEL_POSITION = "VESSEL_POSITION"
    VESSEL_AVAILABILITY = "VESSEL_AVAILABILITY"
    VESSEL_COMMITMENT = "VESSEL_COMMITMENT"
    CARGO_AVAILABLE = "CARGO_AVAILABLE"
    CARGO_UPDATED = "CARGO_UPDATED"
    FIXTURE_CREATED = "FIXTURE_CREATED"
    FREIGHT_UPDATE = "FREIGHT_UPDATE"
    BUNKER_PRICE = "BUNKER_PRICE"
    PORT_UPDATE = "PORT_UPDATE"
    OPERATIONAL_EVENT = "OPERATIONAL_EVENT"
    VOYAGE_STARTED = "VOYAGE_STARTED"
    VOYAGE_COMPLETED = "VOYAGE_COMPLETED"
    CARGO_COMPLETED = "CARGO_COMPLETED"
    IDLE_STARTED = "IDLE_STARTED"
    IDLE_ENDED = "IDLE_ENDED"


class AssociatedDriver(str, Enum):
    ECONOMIC = "economic"
    RELIABILITY = "reliability"
    ROBUSTNESS = "robustness"
    TAIL_RISK = "tail_risk"
    SCHEDULE_FRAGILITY = "schedule_fragility"
