"""
VesselOptima — Phase 11 Decision Governance & Institutional Control
Enums and Reason Codes
"""

from enum import Enum


class PackageStatus(str, Enum):
    """Lifecycle states of a decision package."""
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"


class InstitutionalRole(str, Enum):
    """Institutional roles with strict separation of duties."""
    ANALYST = "ANALYST"
    REVIEWER = "REVIEWER"
    APPROVER = "APPROVER"
    ADMIN = "ADMIN"
    AUDITOR = "AUDITOR"


class AuditEventType(str, Enum):
    """Tamper-evident lifecycle events recorded in hash-chained audit logs."""
    PACKAGE_CREATED = "PACKAGE_CREATED"
    PACKAGE_VALIDATED = "PACKAGE_VALIDATED"
    PACKAGE_SUBMITTED = "PACKAGE_SUBMITTED"
    PACKAGE_REVIEW_STARTED = "PACKAGE_REVIEW_STARTED"
    PACKAGE_APPROVED = "PACKAGE_APPROVED"
    PACKAGE_REJECTED = "PACKAGE_REJECTED"
    PACKAGE_ARCHIVED = "PACKAGE_ARCHIVED"
    PACKAGE_VERSION_CREATED = "PACKAGE_VERSION_CREATED"
    CONFIGURATION_CHANGED = "CONFIGURATION_CHANGED"
    OVERRIDE_RECORDED = "OVERRIDE_RECORDED"
    INTEGRITY_VERIFIED = "INTEGRITY_VERIFIED"
    REPRODUCTION_EXECUTED = "REPRODUCTION_EXECUTED"
    EXPORT_GENERATED = "EXPORT_GENERATED"


class ApprovalStatus(str, Enum):
    """Workflow approval outcomes."""
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"


class GovernanceReasonCode(str, Enum):
    """Deterministic, auditable reason codes for governance checks."""
    GOVERNANCE_CHECKS_PASSED = "GOVERNANCE_CHECKS_PASSED"
    MISSING_OPTIMIZATION_EVIDENCE = "MISSING_OPTIMIZATION_EVIDENCE"
    MISSING_RISK_EVIDENCE = "MISSING_RISK_EVIDENCE"
    MISSING_DECISION_EVIDENCE = "MISSING_DECISION_EVIDENCE"
    INTEGRITY_CHECK_FAILED = "INTEGRITY_CHECK_FAILED"
    SELF_APPROVAL_FORBIDDEN = "SELF_APPROVAL_FORBIDDEN"
    CONFIGURATION_NOT_ACTIVE = "CONFIGURATION_NOT_ACTIVE"
    PACKAGE_ALREADY_FINALIZED = "PACKAGE_ALREADY_FINALIZED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    OVERRIDE_REQUIRES_REASON = "OVERRIDE_REQUIRES_REASON"
    INVALID_AUDIT_CHAIN = "INVALID_AUDIT_CHAIN"
    VERSION_CONFLICT = "VERSION_CONFLICT"
    REPRODUCTION_MISMATCH = "REPRODUCTION_MISMATCH"
    REPRODUCTION_SUCCESS = "REPRODUCTION_SUCCESS"
