"""
VesselOptima — Deterministic Offline Package Generator

Generates the canonical 'demo-v1' offline data package in data/offline/packages/demo-v1/.
All datasets are deterministic, internally consistent, chronologically ordered,
and carry explicit provenance ('SYNTHETIC' or 'PROXY').

DISCLAIMER:
All data generated by this utility is for offline software testing and SIH 2026 demonstration.
None of this data represents verified live market quotes or actual operational ship movements.
"""

from __future__ import annotations

import csv
import math
import os
import random
from datetime import datetime, timedelta, timezone
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent.parent
PACKAGE_DIR = BASE_DIR / "data" / "offline" / "packages" / "demo-v1"


def ensure_dirs():
    for sub in [
        "vessels",
        "vessel_classes",
        "ports",
        "routes",
        "cargo",
        "vessel_positions",
        "market",
        "freight",
        "bunker",
        "congestion",
        "fx",
        "contracts",
        "procurement",
        "idle",
        "employment",
        "scenarios",
    ]:
        (PACKAGE_DIR / sub).mkdir(parents=True, exist_ok=True)


def write_csv(filepath: Path, fieldnames: list[str], rows: list[dict]):
    with open(filepath, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def generate_all():
    random.seed(20260905)
    ensure_dirs()

    print(f"Generating deterministic offline package at: {PACKAGE_DIR}")

    # ──────────────────────────────────────────────────────────────────────────
    # 1. Vessel Classes
    # ──────────────────────────────────────────────────────────────────────────
    vessel_classes = [
        {
            "id": 1,
            "name": "HANDYSIZE",
            "dwt_min": 28000.0,
            "dwt_max": 38000.0,
            "typical_capacity_min": 26000.0,
            "typical_capacity_max": 35000.0,
            "draft_min": 9.5,
            "draft_max": 10.8,
            "loa_min": 170.0,
            "loa_max": 185.0,
            "beam_min": 27.0,
            "beam_max": 29.0,
            "speed_laden": 12.0,
            "speed_ballast": 13.0,
            "consumption_laden": 18.0,
            "consumption_ballast": 16.0,
            "source": "SYNTHETIC_STANDARD_PROFILE",
            "version": 1,
        },
        {
            "id": 2,
            "name": "SUPRAMAX",
            "dwt_min": 50000.0,
            "dwt_max": 64000.0,
            "typical_capacity_min": 48000.0,
            "typical_capacity_max": 60000.0,
            "draft_min": 11.8,
            "draft_max": 13.3,
            "loa_min": 190.0,
            "loa_max": 200.0,
            "beam_min": 32.0,
            "beam_max": 32.3,
            "speed_laden": 12.5,
            "speed_ballast": 13.5,
            "consumption_laden": 24.0,
            "consumption_ballast": 21.0,
            "source": "SYNTHETIC_STANDARD_PROFILE",
            "version": 1,
        },
        {
            "id": 3,
            "name": "PANAMAX",
            "dwt_min": 68000.0,
            "dwt_max": 85000.0,
            "typical_capacity_min": 65000.0,
            "typical_capacity_max": 80000.0,
            "draft_min": 13.5,
            "draft_max": 14.8,
            "loa_min": 220.0,
            "loa_max": 230.0,
            "beam_min": 32.2,
            "beam_max": 32.3,
            "speed_laden": 12.8,
            "speed_ballast": 13.8,
            "consumption_laden": 28.0,
            "consumption_ballast": 24.0,
            "source": "SYNTHETIC_STANDARD_PROFILE",
            "version": 1,
        },
        {
            "id": 4,
            "name": "CAPESIZE",
            "dwt_min": 165000.0,
            "dwt_max": 210000.0,
            "typical_capacity_min": 160000.0,
            "typical_capacity_max": 200000.0,
            "draft_min": 17.5,
            "draft_max": 18.8,
            "loa_min": 285.0,
            "loa_max": 300.0,
            "beam_min": 44.0,
            "beam_max": 46.0,
            "speed_laden": 13.0,
            "speed_ballast": 14.0,
            "consumption_laden": 45.0,
            "consumption_ballast": 38.0,
            "source": "SYNTHETIC_STANDARD_PROFILE",
            "version": 1,
        },
    ]
    write_csv(
        PACKAGE_DIR / "vessel_classes" / "vessel_classes.csv",
        list(vessel_classes[0].keys()),
        vessel_classes,
    )

    # ──────────────────────────────────────────────────────────────────────────
    # 2. Vessels (20 Vessels across the 4 classes)
    # ──────────────────────────────────────────────────────────────────────────
    vessels_data = [
        # Handysize (id 1..4)
        (1, "VO Amber Leader", 1, "IMO9450011", 34500.0, 32000.0, 10.2, 178.5, 28.4, 12.0, 13.0, 17.5, 15.5, "CONTROLLED", "ACTIVE"),
        (2, "VO Coral Trader", 1, "IMO9450022", 36000.0, 33500.0, 10.4, 180.0, 28.6, 12.1, 13.0, 18.0, 15.8, "CONTROLLED", "ACTIVE"),
        (3, "Pacific Falcon", 1, "IMO9450033", 32500.0, 30500.0, 9.9, 175.0, 27.8, 11.8, 12.8, 16.8, 14.8, "NOT_CONTROLLED", "ACTIVE"),
        (4, "Baltic Sprite", 1, "IMO9450044", 37000.0, 34500.0, 10.6, 182.0, 28.8, 12.2, 13.1, 18.2, 16.0, "NOT_CONTROLLED", "ACTIVE"),
        # Supramax (id 5..9)
        (5, "VO Indus Pioneer", 2, "IMO9550055", 58000.0, 55000.0, 12.8, 190.0, 32.2, 12.5, 13.5, 23.5, 20.5, "CONTROLLED", "ACTIVE"),
        (6, "VO Kalinga Star", 2, "IMO9550066", 61000.0, 57500.0, 13.0, 199.9, 32.26, 12.6, 13.6, 24.2, 21.0, "CONTROLLED", "ACTIVE"),
        (7, "Asian Fortune", 2, "IMO9550077", 56500.0, 53500.0, 12.6, 189.9, 32.2, 12.4, 13.4, 23.0, 20.0, "NOT_CONTROLLED", "ACTIVE"),
        (8, "Eastern Horizon", 2, "IMO9550088", 63500.0, 60000.0, 13.2, 199.9, 32.26, 12.8, 13.8, 25.0, 21.5, "NOT_CONTROLLED", "ACTIVE"),
        (9, "Samudra Gem", 2, "IMO9550099", 57200.0, 54000.0, 12.7, 190.0, 32.2, 12.5, 13.5, 23.4, 20.4, "UNKNOWN", "ACTIVE"),
        # Panamax / Kamsarmax (id 10..15)
        (10, "VO Mahanadi Breeze", 3, "IMO9650100", 76000.0, 72500.0, 14.1, 225.0, 32.26, 12.7, 13.7, 27.5, 23.5, "CONTROLLED", "ACTIVE"),
        (11, "VO Utkal Glory", 3, "IMO9650111", 82000.0, 78500.0, 14.5, 229.0, 32.26, 12.9, 13.9, 28.5, 24.5, "CONTROLLED", "ACTIVE"),
        (12, "Ocean Navigator", 3, "IMO9650122", 74500.0, 71000.0, 14.0, 224.5, 32.24, 12.6, 13.6, 26.8, 23.0, "NOT_CONTROLLED", "ACTIVE"),
        (13, "Southern Cross", 3, "IMO9650133", 81500.0, 78000.0, 14.4, 229.0, 32.26, 12.8, 13.8, 28.2, 24.2, "NOT_CONTROLLED", "ACTIVE"),
        (14, "Cape Leeuwin", 3, "IMO9650144", 80000.0, 76500.0, 14.3, 228.0, 32.26, 12.7, 13.7, 28.0, 24.0, "NOT_CONTROLLED", "ACTIVE"),
        (15, "Dhamra Express", 3, "IMO9650155", 82500.0, 79000.0, 14.5, 229.2, 32.26, 12.9, 13.9, 28.8, 24.6, "UNKNOWN", "ACTIVE"),
        # Capesize (id 16..20)
        (16, "VO Bharat Titan", 4, "IMO9750166", 180000.0, 172000.0, 18.2, 292.0, 45.0, 13.0, 14.0, 44.0, 37.0, "CONTROLLED", "ACTIVE"),
        (17, "VO Sagar Samrat", 4, "IMO9750177", 208000.0, 198000.0, 18.6, 299.9, 50.0, 13.2, 14.2, 47.0, 39.5, "CONTROLLED", "ACTIVE"),
        (18, "Pilbara Iron", 4, "IMO9750188", 178000.0, 170000.0, 18.0, 290.0, 45.0, 12.9, 13.9, 43.5, 36.5, "NOT_CONTROLLED", "ACTIVE"),
        (19, "Tubarao Giant", 4, "IMO9750199", 206000.0, 196000.0, 18.5, 299.5, 49.5, 13.1, 14.1, 46.5, 39.0, "NOT_CONTROLLED", "ACTIVE"),
        (20, "Minas Gerais", 4, "IMO9750200", 182000.0, 174000.0, 18.2, 293.0, 45.0, 13.0, 14.0, 44.5, 37.5, "NOT_CONTROLLED", "ACTIVE"),
    ]

    vessels = []
    for row in vessels_data:
        vessels.append({
            "id": row[0],
            "name": row[1],
            "vessel_class_id": row[2],
            "imo_number": row[3],
            "dwt": row[4],
            "cargo_capacity": row[5],
            "draft": row[6],
            "loa": row[7],
            "beam": row[8],
            "speed_laden": row[9],
            "speed_ballast": row[10],
            "consumption_laden": row[11],
            "consumption_ballast": row[12],
            "employment_control": row[13],
            "source": "SYNTHETIC_FLEET_REGISTRY",
            "status": row[14],
            "is_demo": True,
            "version": 1,
        })
    write_csv(PACKAGE_DIR / "vessels" / "vessels.csv", list(vessels[0].keys()), vessels)

    # ──────────────────────────────────────────────────────────────────────────
    # 3. Ports (15 Major Ports)
    # ──────────────────────────────────────────────────────────────────────────
    ports_data = [
        (1, "Paradip", "India", "INPRT", 20.2644, 86.6781, "ACTIVE"),
        (2, "Dhamra", "India", "INDHM", 20.8042, 86.9744, "ACTIVE"),
        (3, "Visakhapatnam", "India", "INVTZ", 17.6868, 83.2185, "ACTIVE"),
        (4, "Haldia", "India", "INHAL", 22.0232, 88.0644, "ACTIVE"),
        (5, "Mundra", "India", "INMUN", 22.7388, 69.7042, "ACTIVE"),
        (6, "Port Hedland", "Australia", "AUPHE", -20.3167, 118.5760, "ACTIVE"),
        (7, "Newcastle", "Australia", "AUNCW", -32.9267, 151.7789, "ACTIVE"),
        (8, "Hay Point", "Australia", "AUHAY", -21.2833, 149.3000, "ACTIVE"),
        (9, "Samarinda", "Indonesia", "IDSMR", -0.5022, 117.1536, "ACTIVE"),
        (10, "Banjarmasin", "Indonesia", "IDBDJ", -3.3194, 114.5908, "ACTIVE"),
        (11, "Richards Bay", "South Africa", "ZARCB", -28.8000, 32.0833, "ACTIVE"),
        (12, "Tubarao", "Brazil", "BRTUB", -20.2889, -40.2458, "ACTIVE"),
        (13, "Singapore", "Singapore", "SGSIN", 1.2903, 103.8520, "ACTIVE"),
        (14, "Rotterdam", "Netherlands", "NLRTM", 51.9244, 4.4777, "ACTIVE"),
        (15, "Qingdao", "China", "CNTAO", 36.0671, 120.3826, "ACTIVE"),
    ]
    ports = [
        {
            "id": p[0],
            "name": p[1],
            "country": p[2],
            "unlocode": p[3],
            "latitude": p[4],
            "longitude": p[5],
            "status": p[6],
        }
        for p in ports_data
    ]
    write_csv(PACKAGE_DIR / "ports" / "ports.csv", list(ports[0].keys()), ports)

    # ──────────────────────────────────────────────────────────────────────────
    # 4. Port Constraints
    # ──────────────────────────────────────────────────────────────────────────
    port_constraints = [
        # Paradip (Port 1): Max draft 14.5m (Kamsarmax max, Cape restricted)
        {"id": 1, "port_id": 1, "terminal": "Central Quay", "berth": "CQ-1/CQ-2", "rule_type": "MAX_DRAFT", "value": 14.5, "unit": "M", "condition": "Tide independent", "effective_from": "2024-01-01 00:00:00", "effective_to": "2027-12-31 23:59:59", "source_url": "SYNTHETIC_BERTH_SCHEDULE", "source_document": "Port Authority Handbook", "verifier": "Chief Marine Surveyor", "verified_at": "2024-01-01 00:00:00", "quality_status": "VALID", "version": 1},
        {"id": 2, "port_id": 1, "terminal": "Central Quay", "berth": "CQ-1/CQ-2", "rule_type": "MAX_LOA", "value": 230.0, "unit": "M", "condition": "Daylight navigation for LOA > 225m", "effective_from": "2024-01-01 00:00:00", "effective_to": "2027-12-31 23:59:59", "source_url": "SYNTHETIC_BERTH_SCHEDULE", "source_document": "Port Authority Handbook", "verifier": "Chief Marine Surveyor", "verified_at": "2024-01-01 00:00:00", "quality_status": "VALID", "version": 1},
        {"id": 3, "port_id": 1, "terminal": "Central Quay", "berth": "CQ-1/CQ-2", "rule_type": "MAX_BEAM", "value": 33.0, "unit": "M", "condition": "Panamax / Kamsarmax beam limit", "effective_from": "2024-01-01 00:00:00", "effective_to": "2027-12-31 23:59:59", "source_url": "SYNTHETIC_BERTH_SCHEDULE", "source_document": "Port Authority Handbook", "verifier": "Chief Marine Surveyor", "verified_at": "2024-01-01 00:00:00", "quality_status": "VALID", "version": 1},
        # Dhamra (Port 2): Deep water, Capesize fully capable (Max draft 18.0m)
        {"id": 4, "port_id": 2, "terminal": "Bulk Berth 1", "berth": "BB-1", "rule_type": "MAX_DRAFT", "value": 18.0, "unit": "M", "condition": "Capesize iron ore / coal berth", "effective_from": "2024-01-01 00:00:00", "effective_to": "2027-12-31 23:59:59", "source_url": "SYNTHETIC_BERTH_SCHEDULE", "source_document": "Port Authority Gazette", "verifier": "Harbour Master", "verified_at": "2024-01-01 00:00:00", "quality_status": "VALID", "version": 1},
        {"id": 5, "port_id": 2, "terminal": "Bulk Berth 1", "berth": "BB-1", "rule_type": "MAX_LOA", "value": 305.0, "unit": "M", "condition": "Unrestricted", "effective_from": "2024-01-01 00:00:00", "effective_to": "2027-12-31 23:59:59", "source_url": "SYNTHETIC_BERTH_SCHEDULE", "source_document": "Port Authority Gazette", "verifier": "Harbour Master", "verified_at": "2024-01-01 00:00:00", "quality_status": "VALID", "version": 1},
        # Visakhapatnam (Port 3): Outer harbour max draft 18.1m
        {"id": 6, "port_id": 3, "terminal": "Outer Harbour", "berth": "OB-1", "rule_type": "MAX_DRAFT", "value": 18.1, "unit": "M", "condition": "Capesize iron ore berth", "effective_from": "2024-01-01 00:00:00", "effective_to": "2027-12-31 23:59:59", "source_url": "SYNTHETIC_BERTH_SCHEDULE", "source_document": "Port Rules", "verifier": "Marine Dept", "verified_at": "2024-01-01 00:00:00", "quality_status": "VALID", "version": 1},
        # Haldia (Port 4): Strict river draft limit 8.5m
        {"id": 7, "port_id": 4, "terminal": "Haldia Dock Complex", "berth": "Berth 4A", "rule_type": "MAX_DRAFT", "value": 8.5, "unit": "M", "condition": "River Hooghly tidal draft; strictly Handysize", "effective_from": "2024-01-01 00:00:00", "effective_to": "2027-12-31 23:59:59", "source_url": "SYNTHETIC_BERTH_SCHEDULE", "source_document": "Pilotage Advisory", "verifier": "River Pilots Assoc", "verified_at": "2024-01-01 00:00:00", "quality_status": "VALID", "version": 1},
        # Port Hedland (Port 6): Capesize iron ore terminal
        {"id": 8, "port_id": 6, "terminal": "Nelson Point", "berth": "Berth A", "rule_type": "MAX_DRAFT", "value": 19.5, "unit": "M", "condition": "Tidal sailing window required for draft > 17.5m", "effective_from": "2024-01-01 00:00:00", "effective_to": "2027-12-31 23:59:59", "source_url": "SYNTHETIC_BERTH_SCHEDULE", "source_document": "Pilbara Port Authority Notice", "verifier": "Port Operations", "verified_at": "2024-01-01 00:00:00", "quality_status": "VALID", "version": 1},
        # Newcastle (Port 7): Coal terminal max draft 15.2m
        {"id": 9, "port_id": 7, "terminal": "PWCS Kooragang", "berth": "K4", "rule_type": "MAX_DRAFT", "value": 15.2, "unit": "M", "condition": "Tidal assistance for deep draft", "effective_from": "2024-01-01 00:00:00", "effective_to": "2027-12-31 23:59:59", "source_url": "SYNTHETIC_BERTH_SCHEDULE", "source_document": "Harbour Master Direction", "verifier": "Port Authority NSW", "verified_at": "2024-01-01 00:00:00", "quality_status": "VALID", "version": 1},
        # Samarinda (Port 9): River anchorage barging max draft 11.5m
        {"id": 10, "port_id": 9, "terminal": "Muara Berau Anchorage", "berth": "Anchorage Point 2", "rule_type": "MAX_DRAFT", "value": 11.5, "unit": "M", "condition": "Floating crane barge loading, geared vessels preferred", "effective_from": "2024-01-01 00:00:00", "effective_to": "2027-12-31 23:59:59", "source_url": "SYNTHETIC_BERTH_SCHEDULE", "source_document": "Indonesian Port Directory", "verifier": "Harbour Master Samarinda", "verified_at": "2024-01-01 00:00:00", "quality_status": "VALID", "version": 1},
    ]
    write_csv(PACKAGE_DIR / "ports" / "port_constraints.csv", list(port_constraints[0].keys()), port_constraints)

    # ──────────────────────────────────────────────────────────────────────────
    # 5. Routes (12 Normalized Maritime Routes)
    # ──────────────────────────────────────────────────────────────────────────
    routes_data = [
        (1, "Port Hedland to Paradip", 6, 1, 3920.0, "SYNTHETIC_VOYAGE_TABLE", 1),
        (2, "Port Hedland to Dhamra", 6, 2, 3950.0, "SYNTHETIC_VOYAGE_TABLE", 1),
        (3, "Newcastle to Paradip", 7, 1, 5250.0, "SYNTHETIC_VOYAGE_TABLE", 1),
        (4, "Newcastle to Visakhapatnam", 7, 3, 5100.0, "SYNTHETIC_VOYAGE_TABLE", 1),
        (5, "Samarinda to Paradip", 9, 1, 2740.0, "SYNTHETIC_VOYAGE_TABLE", 1),
        (6, "Samarinda to Haldia", 9, 4, 2710.0, "SYNTHETIC_VOYAGE_TABLE", 1),
        (7, "Richards Bay to Paradip", 11, 1, 4620.0, "SYNTHETIC_VOYAGE_TABLE", 1),
        (8, "Tubarao to Qingdao", 12, 15, 11050.0, "SYNTHETIC_VOYAGE_TABLE", 1),
        (9, "Tubarao to Paradip", 12, 1, 9200.0, "SYNTHETIC_VOYAGE_TABLE", 1),
        (10, "Paradip to Visakhapatnam (Coastal Reposition)", 1, 3, 190.0, "SYNTHETIC_VOYAGE_TABLE", 1),
        (11, "Paradip to Dhamra (Coastal Reposition)", 1, 2, 55.0, "SYNTHETIC_VOYAGE_TABLE", 1),
        (12, "Singapore to Paradip (Bunker Reposition)", 13, 1, 1620.0, "SYNTHETIC_VOYAGE_TABLE", 1),
    ]
    routes = [
        {
            "id": r[0],
            "name": r[1],
            "origin_port_id": r[2],
            "destination_port_id": r[3],
            "distance_nm": r[4],
            "distance_source": r[5],
            "version": r[6],
        }
        for r in routes_data
    ]
    write_csv(PACKAGE_DIR / "routes" / "routes.csv", list(routes[0].keys()), routes)

    # ──────────────────────────────────────────────────────────────────────────
    # 6. Cargo Requirements (Cargo Parcels)
    # ──────────────────────────────────────────────────────────────────────────
    cargo_parcels = [
        {
            "id": 1,
            "commodity": "COKING_COAL",
            "volume_mt": 75000.0,
            "origin_port_id": 7,  # Newcastle
            "destination_port_id": 1,  # Paradip
            "loading_window_start": "2026-09-15 00:00:00",
            "loading_window_end": "2026-09-22 23:59:59",
            "delivery_deadline": "2026-10-15 23:59:59",
            "tolerance_pct": 5.0,
            "status": "ACTIVE",
            "is_demo": True,
        },
        {
            "id": 2,
            "commodity": "IRON_ORE_FINES",
            "volume_mt": 165000.0,
            "origin_port_id": 6,  # Port Hedland
            "destination_port_id": 2,  # Dhamra
            "loading_window_start": "2026-09-18 00:00:00",
            "loading_window_end": "2026-09-25 23:59:59",
            "delivery_deadline": "2026-10-12 23:59:59",
            "tolerance_pct": 10.0,
            "status": "ACTIVE",
            "is_demo": True,
        },
        {
            "id": 3,
            "commodity": "THERMAL_COAL",
            "volume_mt": 55000.0,
            "origin_port_id": 9,  # Samarinda
            "destination_port_id": 1,  # Paradip
            "loading_window_start": "2026-09-20 00:00:00",
            "loading_window_end": "2026-09-27 23:59:59",
            "delivery_deadline": "2026-10-10 23:59:59",
            "tolerance_pct": 5.0,
            "status": "ACTIVE",
            "is_demo": True,
        },
        {
            "id": 4,
            "commodity": "THERMAL_COAL",
            "volume_mt": 32000.0,
            "origin_port_id": 9,  # Samarinda
            "destination_port_id": 4,  # Haldia (Handysize limit)
            "loading_window_start": "2026-09-22 00:00:00",
            "loading_window_end": "2026-09-28 23:59:59",
            "delivery_deadline": "2026-10-12 23:59:59",
            "tolerance_pct": 5.0,
            "status": "ACTIVE",
            "is_demo": True,
        },
        {
            "id": 5,
            "commodity": "PCI_COAL",
            "volume_mt": 72000.0,
            "origin_port_id": 11,  # Richards Bay
            "destination_port_id": 3,  # Visakhapatnam
            "loading_window_start": "2026-09-25 00:00:00",
            "loading_window_end": "2026-10-02 23:59:59",
            "delivery_deadline": "2026-10-25 23:59:59",
            "tolerance_pct": 5.0,
            "status": "ACTIVE",
            "is_demo": True,
        },
        {
            "id": 6,
            "commodity": "COKING_COAL",
            "volume_mt": 150000.0,
            "origin_port_id": 8,  # Hay Point
            "destination_port_id": 2,  # Dhamra (Cape capable)
            "loading_window_start": "2026-10-01 00:00:00",
            "loading_window_end": "2026-10-08 23:59:59",
            "delivery_deadline": "2026-10-28 23:59:59",
            "tolerance_pct": 5.0,
            "status": "ACTIVE",
            "is_demo": True,
        },
    ]
    write_csv(PACKAGE_DIR / "cargo" / "cargo_requirements.csv", list(cargo_parcels[0].keys()), cargo_parcels)

    # ──────────────────────────────────────────────────────────────────────────
    # 7. Vessel Positions & Commitments
    # ──────────────────────────────────────────────────────────────────────────
    vessel_positions = [
        {"id": 1, "vessel_profile_id": 1, "available_at": "2026-09-10 12:00:00", "location_port_id": 1, "location_description": "Discharged Paradip anchorage", "source": "SYNTHETIC_AGENT_REPORT", "confidence": 0.98, "data_kind": "SYNTHETIC"},
        {"id": 2, "vessel_profile_id": 2, "available_at": "2026-09-12 08:00:00", "location_port_id": 4, "location_description": "Haldia berth waiting completion", "source": "SYNTHETIC_AGENT_REPORT", "confidence": 0.95, "data_kind": "SYNTHETIC"},
        {"id": 3, "vessel_profile_id": 5, "available_at": "2026-09-14 00:00:00", "location_port_id": 13, "location_description": "Singapore bunkering completed", "source": "SYNTHETIC_AGENT_REPORT", "confidence": 0.99, "data_kind": "SYNTHETIC"},
        {"id": 4, "vessel_profile_id": 6, "available_at": "2026-09-08 18:00:00", "location_port_id": 1, "location_description": "Paradip discharged, awaiting orders", "source": "SYNTHETIC_AGENT_REPORT", "confidence": 0.97, "data_kind": "SYNTHETIC"},
        {"id": 5, "vessel_profile_id": 10, "available_at": "2026-09-15 06:00:00", "location_port_id": 13, "location_description": "Singapore outer roads", "source": "SYNTHETIC_AGENT_REPORT", "confidence": 0.96, "data_kind": "SYNTHETIC"},
        {"id": 6, "vessel_profile_id": 11, "available_at": "2026-09-11 14:00:00", "location_port_id": 2, "location_description": "Dhamra coal discharge complete", "source": "SYNTHETIC_AGENT_REPORT", "confidence": 0.99, "data_kind": "SYNTHETIC"},
        {"id": 7, "vessel_profile_id": 16, "available_at": "2026-09-18 00:00:00", "location_port_id": 2, "location_description": "Dhamra iron ore berth", "source": "SYNTHETIC_AGENT_REPORT", "confidence": 0.98, "data_kind": "SYNTHETIC"},
        {"id": 8, "vessel_profile_id": 17, "available_at": "2026-09-20 12:00:00", "location_port_id": 6, "location_description": "Port Hedland ballast approach", "source": "SYNTHETIC_AGENT_REPORT", "confidence": 0.95, "data_kind": "SYNTHETIC"},
    ]
    write_csv(PACKAGE_DIR / "vessel_positions" / "vessel_positions.csv", list(vessel_positions[0].keys()), vessel_positions)

    vessel_commitments = [
        {"id": 1, "vessel_profile_id": 1, "commitment_start": "2026-09-24 00:00:00", "commitment_end": "2026-10-14 23:59:59", "route_description": "Committed coastal coal shuttle Paradip-Tuticorin", "status": "CONFIRMED", "is_immutable": True, "employment_control_ref": "TIME_CHARTER_CT_2026_09", "source": "SYNTHETIC_FIXTURE_RECORD"},
        {"id": 2, "vessel_profile_id": 6, "commitment_start": "2026-09-26 00:00:00", "commitment_end": "2026-10-18 23:59:59", "route_description": "Committed Samarinda to Paradip coal voyage", "status": "CONFIRMED", "is_immutable": True, "employment_control_ref": "COA_SCHEDULE_VO_2026", "source": "SYNTHETIC_FIXTURE_RECORD"},
        {"id": 3, "vessel_profile_id": 11, "commitment_start": "2026-09-28 00:00:00", "commitment_end": "2026-10-25 23:59:59", "route_description": "Committed Newcastle to Dhamra coking coal voyage", "status": "CONFIRMED", "is_immutable": True, "employment_control_ref": "TIME_CHARTER_CT_2026_04", "source": "SYNTHETIC_FIXTURE_RECORD"},
        {"id": 4, "vessel_profile_id": 16, "commitment_start": "2026-10-05 00:00:00", "commitment_end": "2026-11-02 23:59:59", "route_description": "Committed Port Hedland to Dhamra iron ore voyage", "status": "CONFIRMED", "is_immutable": True, "employment_control_ref": "LONG_TERM_CHARTER_TITAN", "source": "SYNTHETIC_FIXTURE_RECORD"},
    ]
    write_csv(PACKAGE_DIR / "vessel_positions" / "vessel_commitments.csv", list(vessel_commitments[0].keys()), vessel_commitments)

    # ──────────────────────────────────────────────────────────────────────────
    # 8. Time Series Data (2024-01-01 to 2026-08-31 = 974 days)
    # ──────────────────────────────────────────────────────────────────────────
    start_date = datetime(2024, 1, 1, 0, 0, 0)
    end_date = datetime(2026, 8, 31, 0, 0, 0)
    total_days = (end_date - start_date).days + 1

    market_indices = []
    freight_observations = []
    fuel_prices = []
    congestion_observations = []
    fx_observations = []

    obs_id = 1
    freight_id = 1
    fuel_id = 1
    cong_id = 1
    fx_id = 1

    for day_idx in range(total_days):
        current_date = start_date + timedelta(days=day_idx)
        date_str = current_date.strftime("%Y-%m-%d 00:00:00")
        avail_str = (current_date + timedelta(hours=18)).strftime("%Y-%m-%d %H:%M:%S")

        # Annual seasonality cycle (t in [0, 2*pi])
        t_annual = (day_idx % 365) / 365.0 * 2.0 * math.pi
        # Multi-month wave
        t_cycle = day_idx / 60.0 * 2.0 * math.pi

        # Macro trend: moderate growth + cycle
        trend_factor = 1.0 + 0.08 * (day_idx / total_days)

        # Geopolitical shock: Nov 2024 Red Sea event (days ~ 320 to 380)
        shock_red_sea = 0.0
        if 320 <= day_idx <= 380:
            shock_red_sea = 0.25 * math.sin((day_idx - 320) / 60.0 * math.pi)

        # Weather / Monsoon shock in Bay of Bengal: July/August of each year
        monsoon_shock = 0.0
        month = current_date.month
        if month in [6, 7, 8]:
            monsoon_shock = 0.12 * math.sin(((day_idx % 365) - 150) / 90.0 * math.pi)

        # Noise component (deterministic PRNG)
        noise_bdi = random.gauss(0, 25)
        noise_cape = random.gauss(0, 45)
        noise_panamax = random.gauss(0, 20)
        noise_supra = random.gauss(0, 15)
        noise_handy = random.gauss(0, 10)

        # Baltic Indices calculation
        # Base levels: BDI ~1600, BCI ~2400, BPI ~1550, BSI ~1200, BHSI ~750
        seasonal_mult = 1.0 + 0.20 * math.sin(t_annual - 1.2) + 0.08 * math.sin(t_cycle)
        total_mult = (seasonal_mult + shock_red_sea) * trend_factor

        bdi_val = round(max(800.0, 1600.0 * total_mult + noise_bdi), 1)
        bci_val = round(max(1000.0, 2400.0 * total_mult * (1.0 + 0.15 * math.sin(t_annual)) + noise_cape), 1)
        bpi_val = round(max(900.0, 1550.0 * total_mult + noise_panamax), 1)
        bsi_val = round(max(700.0, 1200.0 * total_mult + noise_supra), 1)
        bhsi_val = round(max(450.0, 750.0 * total_mult + noise_handy), 1)

        for s_id, val in [
            ("INDEX_BDI", bdi_val),
            ("INDEX_BCI", bci_val),
            ("INDEX_BPI", bpi_val),
            ("INDEX_BSI", bsi_val),
            ("INDEX_BHSI", bhsi_val),
        ]:
            market_indices.append({
                "id": obs_id,
                "series_id": s_id,
                "observed_at": date_str,
                "available_at": avail_str,
                "value": val,
                "unit": "POINTS",
                "source_id": 1,
                "source_version": "v1.0",
                "quality_status": "VALID",
                "data_kind": "SYNTHETIC",
                "content_hash": f"hash_mkt_{obs_id:06d}",
                "is_demo": True,
            })
            obs_id += 1

        # Route Freight Observations (USD / MT)
        # 1. Port Hedland -> Paradip (Capesize Iron Ore)
        fr_cape_hedland = round(max(8.0, 13.5 * total_mult + random.gauss(0, 0.3)), 2)
        # 2. Newcastle -> Paradip (Panamax Coking Coal)
        fr_pan_newcastle = round(max(10.0, 17.2 * total_mult + random.gauss(0, 0.35)), 2)
        # 3. Samarinda -> Paradip (Supramax Thermal Coal)
        fr_supra_samarinda = round(max(6.5, 10.8 * total_mult + random.gauss(0, 0.25)), 2)
        # 4. Richards Bay -> Paradip (Panamax Coal)
        fr_pan_rbay = round(max(9.5, 15.4 * total_mult + random.gauss(0, 0.3)), 2)
        # 5. Tubarao -> Qingdao (Capesize C3 benchmark)
        fr_cape_c3 = round(max(15.0, 24.5 * total_mult + random.gauss(0, 0.5)), 2)

        for s_id, val in [
            ("FREIGHT_AU_HEDLAND_PARADIP_CAPE", fr_cape_hedland),
            ("FREIGHT_AU_NEWCASTLE_PARADIP_PANAMAX", fr_pan_newcastle),
            ("FREIGHT_ID_SAMARINDA_PARADIP_SUPRA", fr_supra_samarinda),
            ("FREIGHT_ZA_RICHARDSBAY_PARADIP_PANAMAX", fr_pan_rbay),
            ("FREIGHT_BR_TUBARAO_QINGDAO_CAPE", fr_cape_c3),
        ]:
            freight_observations.append({
                "id": freight_id,
                "series_id": s_id,
                "observed_at": date_str,
                "available_at": avail_str,
                "value": val,
                "unit": "USD_PER_MT",
                "source_id": 1,
                "source_version": "v1.0",
                "quality_status": "VALID",
                "data_kind": "PROXY",
                "content_hash": f"hash_fr_{freight_id:06d}",
                "is_demo": True,
            })
            freight_id += 1

        # Bunker Fuel Prices (USD / MT)
        # VLSFO: base $620, IFO380: base $460, MGO: base $810
        bunker_mult = 1.0 + 0.10 * math.sin(t_annual + 0.5) + (0.15 if 450 <= day_idx <= 520 else 0.0)
        vlsfo_sin = round(max(480.0, 620.0 * bunker_mult + random.gauss(0, 4.0)), 2)
        ifo380_sin = round(max(350.0, 460.0 * bunker_mult + random.gauss(0, 3.5)), 2)
        mgo_sin = round(max(650.0, 810.0 * bunker_mult + random.gauss(0, 5.0)), 2)
        vlsfo_rtm = round(max(450.0, 590.0 * bunker_mult + random.gauss(0, 4.0)), 2)
        vlsfo_prt = round(max(510.0, 655.0 * bunker_mult + random.gauss(0, 4.5)), 2)  # Paradip delivery premium

        for s_id, val in [
            ("BUNKER_VLSFO_SINGAPORE", vlsfo_sin),
            ("BUNKER_IFO380_SINGAPORE", ifo380_sin),
            ("BUNKER_MGO_SINGAPORE", mgo_sin),
            ("BUNKER_VLSFO_ROTTERDAM", vlsfo_rtm),
            ("BUNKER_VLSFO_PARADIP", vlsfo_prt),
        ]:
            fuel_prices.append({
                "id": fuel_id,
                "series_id": s_id,
                "observed_at": date_str,
                "available_at": avail_str,
                "value": val,
                "unit": "USD_PER_MT",
                "source_id": 2,
                "source_version": "v1.0",
                "quality_status": "VALID",
                "data_kind": "SYNTHETIC",
                "content_hash": f"hash_bnk_{fuel_id:06d}",
                "is_demo": True,
            })
            fuel_id += 1

        # Congestion Observations (Days Waiting)
        cong_paradip = round(max(1.0, 4.2 + monsoon_shock * 8.0 + random.gauss(0, 0.4)), 1)
        cong_dhamra = round(max(0.5, 2.1 + monsoon_shock * 3.0 + random.gauss(0, 0.2)), 1)
        cong_newcastle = round(max(2.0, 5.5 + 2.5 * math.sin(t_annual) + random.gauss(0, 0.6)), 1)
        cong_hedland = round(max(1.0, 2.8 + random.gauss(0, 0.3)), 1)

        for s_id, val in [
            ("CONGESTION_PORT_PARADIP", cong_paradip),
            ("CONGESTION_PORT_DHAMRA", cong_dhamra),
            ("CONGESTION_PORT_NEWCASTLE", cong_newcastle),
            ("CONGESTION_PORT_HEDLAND", cong_hedland),
        ]:
            congestion_observations.append({
                "id": cong_id,
                "series_id": s_id,
                "observed_at": date_str,
                "available_at": avail_str,
                "value": val,
                "unit": "DAYS",
                "source_id": 3,
                "source_version": "v1.0",
                "quality_status": "VALID",
                "data_kind": "SYNTHETIC",
                "content_hash": f"hash_cng_{cong_id:06d}",
                "is_demo": True,
            })
            cong_id += 1

        # Foreign Exchange (USD/INR, USD/EUR)
        fx_inr = round(82.8 + 0.002 * day_idx + random.gauss(0, 0.08), 4)
        fx_eur = round(0.915 + 0.00003 * day_idx + random.gauss(0, 0.002), 4)

        for s_id, val, u in [
            ("FX_USD_INR", fx_inr, "INR_PER_USD"),
            ("FX_USD_EUR", fx_eur, "EUR_PER_USD"),
        ]:
            fx_observations.append({
                "id": fx_id,
                "series_id": s_id,
                "observed_at": date_str,
                "available_at": avail_str,
                "value": val,
                "unit": u,
                "source_id": 4,
                "source_version": "v1.0",
                "quality_status": "VALID",
                "data_kind": "SYNTHETIC",
                "content_hash": f"hash_fx_{fx_id:06d}",
                "is_demo": True,
            })
            fx_id += 1

    write_csv(PACKAGE_DIR / "market" / "market_indices.csv", list(market_indices[0].keys()), market_indices)
    write_csv(PACKAGE_DIR / "freight" / "freight_observations.csv", list(freight_observations[0].keys()), freight_observations)
    write_csv(PACKAGE_DIR / "bunker" / "fuel_prices.csv", list(fuel_prices[0].keys()), fuel_prices)
    write_csv(PACKAGE_DIR / "congestion" / "congestion_observations.csv", list(congestion_observations[0].keys()), congestion_observations)
    write_csv(PACKAGE_DIR / "fx" / "fx_observations.csv", list(fx_observations[0].keys()), fx_observations)

    # ──────────────────────────────────────────────────────────────────────────
    # 9. Contracts & Procurement Windows
    # ──────────────────────────────────────────────────────────────────────────
    contracts = [
        {"id": 1, "contract_id": "CT-SPOT-VO-01", "vessel_class": "PANAMAX", "contract_type": "SPOT", "duration_days": 25, "fixed_rate_usd_day": 16500.0, "min_volume_mt": 70000.0, "max_volume_mt": 80000.0, "bunker_adjustment_clause": False, "notice_days": 3, "is_demo": True},
        {"id": 2, "contract_id": "CT-COA-AUS-2026", "vessel_class": "PANAMAX", "contract_type": "MULTI_VOYAGE", "duration_days": 180, "fixed_rate_usd_day": 14800.0, "min_volume_mt": 400000.0, "max_volume_mt": 600000.0, "bunker_adjustment_clause": True, "notice_days": 14, "is_demo": True},
        {"id": 3, "contract_id": "CT-TC-SUPRA-6M", "vessel_class": "SUPRAMAX", "contract_type": "SHORT_TERM", "duration_days": 180, "fixed_rate_usd_day": 13200.0, "min_volume_mt": 50000.0, "max_volume_mt": 60000.0, "bunker_adjustment_clause": True, "notice_days": 7, "is_demo": True},
        {"id": 4, "contract_id": "CT-TC-CAPE-1Y", "vessel_class": "CAPESIZE", "contract_type": "MEDIUM_TERM", "duration_days": 365, "fixed_rate_usd_day": 23500.0, "min_volume_mt": 1200000.0, "max_volume_mt": 1800000.0, "bunker_adjustment_clause": True, "notice_days": 30, "is_demo": True},
    ]
    write_csv(PACKAGE_DIR / "contracts" / "contracts.csv", list(contracts[0].keys()), contracts)

    procurement_windows = [
        {"id": 1, "cargo_id": 1, "strategy": "SPOT", "window_start": "2026-09-08 00:00:00", "window_end": "2026-09-18 23:59:59", "lead_time_days": 10, "target_rate_usd_mt": 17.50, "risk_buffer_pct": 5.0, "status": "OPEN", "is_demo": True},
        {"id": 2, "cargo_id": 2, "strategy": "MULTI_VOYAGE", "window_start": "2026-09-10 00:00:00", "window_end": "2026-09-22 23:59:59", "lead_time_days": 12, "target_rate_usd_mt": 13.80, "risk_buffer_pct": 7.5, "status": "OPEN", "is_demo": True},
        {"id": 3, "cargo_id": 3, "strategy": "SPOT", "window_start": "2026-09-12 00:00:00", "window_end": "2026-09-24 23:59:59", "lead_time_days": 8, "target_rate_usd_mt": 11.20, "risk_buffer_pct": 5.0, "status": "OPEN", "is_demo": True},
        {"id": 4, "cargo_id": 5, "strategy": "SHORT_TERM", "window_start": "2026-09-15 00:00:00", "window_end": "2026-09-30 23:59:59", "lead_time_days": 15, "target_rate_usd_mt": 15.60, "risk_buffer_pct": 6.0, "status": "OPEN", "is_demo": True},
    ]
    write_csv(PACKAGE_DIR / "procurement" / "procurement_windows.csv", list(procurement_windows[0].keys()), procurement_windows)

    # ──────────────────────────────────────────────────────────────────────────
    # 10. Idle Windows & Employment Candidates / Evaluations
    # ──────────────────────────────────────────────────────────────────────────
    idle_windows = [
        # Vessel 1: Available 2026-09-10 at Paradip; Next commitment 2026-09-24 -> 14 days idle window
        {"id": 1, "vessel_profile_id": 1, "availability_event_id": 1, "commitment_id": 1, "window_start": "2026-09-10 12:00:00", "window_end": "2026-09-24 00:00:00", "idle_days": 13.5, "employment_control": "CONTROLLED", "is_actionable": True, "selected_action": "ALTERNATIVE_EMPLOYMENT", "status": "EVALUATED"},
        # Vessel 6: Available 2026-09-08 at Paradip; Next commitment 2026-09-26 -> 18 days idle window
        {"id": 2, "vessel_profile_id": 6, "availability_event_id": 4, "commitment_id": 2, "window_start": "2026-09-08 18:00:00", "window_end": "2026-09-26 00:00:00", "idle_days": 17.25, "employment_control": "CONTROLLED", "is_actionable": True, "selected_action": "REPOSITION", "status": "EVALUATED"},
        # Vessel 11: Available 2026-09-11 at Dhamra; Next commitment 2026-09-28 -> 17 days idle window
        {"id": 3, "vessel_profile_id": 11, "availability_event_id": 6, "commitment_id": 3, "window_start": "2026-09-11 14:00:00", "window_end": "2026-09-28 00:00:00", "idle_days": 16.4, "employment_control": "CONTROLLED", "is_actionable": True, "selected_action": "WAIT", "status": "EVALUATED"},
    ]
    write_csv(PACKAGE_DIR / "idle" / "idle_windows.csv", list(idle_windows[0].keys()), idle_windows)

    employment_candidates = [
        # Candidate 1: Vessel 1 carrying Cargo 4 (Haldia thermal coal) during idle window
        {"id": 1, "vessel_profile_id": 1, "route_id": 6, "cargo_parcel_id": 4, "contract_strategy": "SPOT", "estimated_freight_cost": 345000.0, "estimated_bunker_cost": 84000.0, "estimated_port_cost": 35000.0, "estimated_total_cost": 464000.0, "arrival_date": "2026-09-22 18:00:00", "max_voyages": 1, "eligibility": True, "eligibility_reason": "Feasible: Handysize matches Haldia draft limit (8.5m) and completes before next commitment", "data_kind": "DERIVED", "is_demo": True},
        # Candidate 2: Vessel 6 repositioning to Samarinda for next COA commitment
        {"id": 2, "vessel_profile_id": 6, "route_id": 5, "cargo_parcel_id": 3, "contract_strategy": "SPOT", "estimated_freight_cost": 590000.0, "estimated_bunker_cost": 142000.0, "estimated_port_cost": 42000.0, "estimated_total_cost": 774000.0, "arrival_date": "2026-09-19 12:00:00", "max_voyages": 1, "eligibility": True, "eligibility_reason": "Feasible: Supramax fits Samarinda draft and arrives before next loading", "data_kind": "DERIVED", "is_demo": True},
        # Candidate 3: Vessel 11 repositioning to Singapore for bunkering
        {"id": 3, "vessel_profile_id": 11, "route_id": 12, "cargo_parcel_id": 1, "contract_strategy": "SPOT", "estimated_freight_cost": 1240000.0, "estimated_bunker_cost": 210000.0, "estimated_port_cost": 55000.0, "estimated_total_cost": 1505000.0, "arrival_date": "2026-09-20 00:00:00", "max_voyages": 1, "eligibility": True, "eligibility_reason": "Feasible: Panamax vessel capacity and schedule preserve next Newcastle commitment", "data_kind": "DERIVED", "is_demo": True},
    ]
    write_csv(PACKAGE_DIR / "employment" / "employment_candidates.csv", list(employment_candidates[0].keys()), employment_candidates)

    employment_evaluations = [
        # Actions for Evaluation 1 (Vessel 1)
        {"id": 1, "evaluation_id": 1, "action_type": "WAIT", "is_feasible": True, "feasibility_reason": "Always feasible; anchor at Paradip anchorage", "idle_cost": 67500.0, "reposition_cost": 0.0, "bunker_cost": 16200.0, "port_cost": 8500.0, "expected_contribution": 0.0, "total_expected_cost": 92200.0, "risk_score": 0.15, "is_selected": False, "reason_codes": '["BASELINE_COMPARATOR", "UNPRODUCTIVE_CAPITAL_EXPOSURE"]'},
        {"id": 2, "evaluation_id": 1, "action_type": "REPOSITION", "is_feasible": True, "feasibility_reason": "Reposition to Visakhapatnam for drydock inspection", "idle_cost": 15000.0, "reposition_cost": 22000.0, "bunker_cost": 18500.0, "port_cost": 12000.0, "expected_contribution": 0.0, "total_expected_cost": 67500.0, "risk_score": 0.22, "is_selected": False, "reason_codes": '["REPOSITION_COST_EXCEEDS_BENEFIT"]'},
        {"id": 3, "evaluation_id": 1, "action_type": "ALTERNATIVE_EMPLOYMENT", "is_feasible": True, "feasibility_reason": "Feasible short parcel employment (Cargo 4 Samarinda-Haldia coal)", "idle_cost": 0.0, "reposition_cost": 18000.0, "bunker_cost": 65000.0, "port_cost": 32000.0, "expected_contribution": 145000.0, "total_expected_cost": -30000.0, "risk_score": 0.28, "is_selected": True, "reason_codes": '["NET_POSITIVE_CONTRIBUTION", "SCHEDULE_COMPATIBLE", "EMPLOYMENT_RIGHTS_VERIFIED"]'},
        # Actions for Evaluation 2 (Vessel 6)
        {"id": 4, "evaluation_id": 2, "action_type": "WAIT", "is_feasible": True, "feasibility_reason": "Anchorage wait at Paradip 17 days", "idle_cost": 103500.0, "reposition_cost": 0.0, "bunker_cost": 24000.0, "port_cost": 12000.0, "expected_contribution": 0.0, "total_expected_cost": 139500.0, "risk_score": 0.35, "is_selected": False, "reason_codes": '["HIGH_IDLE_DAYS_EXPOSURE"]'},
        {"id": 5, "evaluation_id": 2, "action_type": "REPOSITION", "is_feasible": True, "feasibility_reason": "Slow-steam repositioning towards Samarinda loading zone", "idle_cost": 20000.0, "reposition_cost": 48000.0, "bunker_cost": 38000.0, "port_cost": 15000.0, "expected_contribution": 0.0, "total_expected_cost": 121000.0, "risk_score": 0.18, "is_selected": True, "reason_codes": '["SLOW_STEAM_BUNKER_SAVINGS", "OPTIMAL_POSITIONING_FOR_NEXT_COMMITMENT"]'},
        # Actions for Evaluation 3 (Vessel 11)
        {"id": 6, "evaluation_id": 3, "action_type": "WAIT", "is_feasible": True, "feasibility_reason": "Controlled wait at Dhamra deep berth buffer", "idle_cost": 95000.0, "reposition_cost": 0.0, "bunker_cost": 22000.0, "port_cost": 11000.0, "expected_contribution": 0.0, "total_expected_cost": 128000.0, "risk_score": 0.12, "is_selected": True, "reason_codes": '["WEATHER_WINDOW_SAFETY", "NEXT_VOYAGE_READY"]'},
    ]
    write_csv(PACKAGE_DIR / "employment" / "employment_evaluations.csv", list(employment_evaluations[0].keys()), employment_evaluations)

    # ──────────────────────────────────────────────────────────────────────────
    # 11. Scenarios
    # ──────────────────────────────────────────────────────────────────────────
    scenarios = [
        {"id": 1, "name": "BASE", "description": "Baseline deterministic market parameters under current trend and seasonality.", "scenario_type": "BASE", "parameters": '{"bunker_multiplier": 1.0, "freight_multiplier": 1.0, "congestion_days_delta": 0, "demand_buffer_pct": 0.0}', "input_manifest_hash": "manifest_hash_base", "runtime_mode": "OFFLINE_DEMO", "is_demo": True},
        {"id": 2, "name": "FUEL_SHOCK_PLUS_20", "description": "Global bunker surge scenario: VLSFO and MGO prices increase by 20%.", "scenario_type": "STRESS", "parameters": '{"bunker_multiplier": 1.20, "freight_multiplier": 1.05, "congestion_days_delta": 0, "demand_buffer_pct": 0.0}', "input_manifest_hash": "manifest_hash_base", "runtime_mode": "OFFLINE_DEMO", "is_demo": True},
        {"id": 3, "name": "FREIGHT_SPIKE_PLUS_15", "description": "Baltic dry bulk index and spot freight rates jump by 15% due to tonnage squeeze.", "scenario_type": "STRESS", "parameters": '{"bunker_multiplier": 1.0, "freight_multiplier": 1.15, "congestion_days_delta": 0, "demand_buffer_pct": 0.0}', "input_manifest_hash": "manifest_hash_base", "runtime_mode": "OFFLINE_DEMO", "is_demo": True},
        {"id": 4, "name": "CONGESTION_SPIKE_EAST_COAST", "description": "Severe monsoon queuing at Paradip and Dhamra adds 5 waiting days per port call.", "scenario_type": "OPERATIONAL", "parameters": '{"bunker_multiplier": 1.0, "freight_multiplier": 1.0, "congestion_days_delta": 5, "demand_buffer_pct": -5.0}', "input_manifest_hash": "manifest_hash_base", "runtime_mode": "OFFLINE_DEMO", "is_demo": True},
        {"id": 5, "name": "CYCLONE_MONSOON_DISRUPTION", "description": "Combined weather disruption: 6-day port closure, 15% bunker surge, 10% freight rally.", "scenario_type": "COMPOUND", "parameters": '{"bunker_multiplier": 1.15, "freight_multiplier": 1.10, "congestion_days_delta": 6, "demand_buffer_pct": -10.0}', "input_manifest_hash": "manifest_hash_base", "runtime_mode": "OFFLINE_DEMO", "is_demo": True},
    ]
    write_csv(PACKAGE_DIR / "scenarios" / "scenarios.csv", list(scenarios[0].keys()), scenarios)

    print("Successfully generated all CSV files for package demo-v1.")


if __name__ == "__main__":
    generate_all()
