"""initial_schema

Revision ID: 78d9609f5cd5
Revises: 
Create Date: 2026-09-05 01:28:49.157733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d9609f5cd5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('evaluation_start', sa.DateTime(), nullable=True),
    sa.Column('evaluation_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('runtime_mode', sa.Enum('LIVE', 'OFFLINE_DEMO', name='runtimemodeenum'), nullable=False),
    sa.Column('data_context_id', sa.String(length=64), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('licence_class', sa.String(length=100), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('refresh_sla', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('artifact_hash', sa.String(length=128), nullable=True),
    sa.Column('runtime_mode', sa.Enum('LIVE', 'OFFLINE_DEMO', name='runtimemodeenum'), nullable=False),
    sa.Column('data_context_id', sa.String(length=64), nullable=True),
    sa.Column('offline_package_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offline_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('manifest_hash', sa.String(length=128), nullable=False),
    sa.Column('coverage_start', sa.DateTime(), nullable=True),
    sa.Column('coverage_end', sa.DateTime(), nullable=True),
    sa.Column('builder_commit', sa.String(length=64), nullable=True),
    sa.Column('validator_version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offline_packages_package_id'), 'offline_packages', ['package_id'], unique=True)
    op.create_table('ports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('unlocode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unlocode')
    )
    op.create_table('runtime_mode_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mode', sa.Enum('LIVE', 'OFFLINE_DEMO', name='runtimemodeenum'), nullable=False),
    sa.Column('mode_session_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('selected_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_mode_events_mode_session_id'), 'runtime_mode_events', ['mode_session_id'], unique=True)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scenario_type', sa.String(length=64), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('input_manifest_hash', sa.String(length=128), nullable=True),
    sa.Column('runtime_mode', sa.Enum('LIVE', 'OFFLINE_DEMO', name='runtimemodeenum'), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vessel_classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('dwt_min', sa.Float(), nullable=True),
    sa.Column('dwt_max', sa.Float(), nullable=True),
    sa.Column('typical_capacity_min', sa.Float(), nullable=True),
    sa.Column('typical_capacity_max', sa.Float(), nullable=True),
    sa.Column('draft_min', sa.Float(), nullable=True),
    sa.Column('draft_max', sa.Float(), nullable=True),
    sa.Column('loa_min', sa.Float(), nullable=True),
    sa.Column('loa_max', sa.Float(), nullable=True),
    sa.Column('beam_min', sa.Float(), nullable=True),
    sa.Column('beam_max', sa.Float(), nullable=True),
    sa.Column('speed_laden', sa.Float(), nullable=True),
    sa.Column('speed_ballast', sa.Float(), nullable=True),
    sa.Column('consumption_laden', sa.Float(), nullable=True),
    sa.Column('consumption_ballast', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cargo_parcels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commodity', sa.String(length=128), nullable=False),
    sa.Column('volume_mt', sa.Float(), nullable=False),
    sa.Column('origin_port_id', sa.Integer(), nullable=True),
    sa.Column('destination_port_id', sa.Integer(), nullable=True),
    sa.Column('loading_window_start', sa.DateTime(), nullable=True),
    sa.Column('loading_window_end', sa.DateTime(), nullable=True),
    sa.Column('delivery_deadline', sa.DateTime(), nullable=True),
    sa.Column('tolerance_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['destination_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['origin_port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_run_id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('lower_80', sa.Float(), nullable=True),
    sa.Column('upper_80', sa.Float(), nullable=True),
    sa.Column('lower_95', sa.Float(), nullable=True),
    sa.Column('upper_95', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.String(length=128), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('quality_status', sa.Enum('VALID', 'STALE', 'UNKNOWN', 'REJECTED', name='qualitystatusenum'), nullable=True),
    sa.Column('data_kind', sa.Enum('OBSERVED', 'PROXY', 'DERIVED', 'SYNTHETIC', 'MODEL_PREDICTION', name='datakindenum'), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_obs_series_available', 'market_observations', ['series_id', 'available_at'], unique=False)
    op.create_index('ix_market_obs_series_observed', 'market_observations', ['series_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_market_observations_series_id'), 'market_observations', ['series_id'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'OPTIMAL', 'INFEASIBLE', 'ERROR', name='optimizationstatusenum'), nullable=True),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('solver_version', sa.String(length=64), nullable=True),
    sa.Column('solve_time_seconds', sa.Float(), nullable=True),
    sa.Column('runtime_mode', sa.Enum('LIVE', 'OFFLINE_DEMO', name='runtimemodeenum'), nullable=False),
    sa.Column('data_context_id', sa.String(length=64), nullable=True),
    sa.Column('offline_package_id', sa.String(length=64), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('infeasibility_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('port_constraints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('terminal', sa.String(length=255), nullable=True),
    sa.Column('berth', sa.String(length=255), nullable=True),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_document', sa.String(length=512), nullable=True),
    sa.Column('verifier', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('quality_status', sa.Enum('VALID', 'STALE', 'UNKNOWN', 'REJECTED', name='qualitystatusenum'), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('origin_port_id', sa.Integer(), nullable=True),
    sa.Column('destination_port_id', sa.Integer(), nullable=True),
    sa.Column('distance_nm', sa.Float(), nullable=True),
    sa.Column('distance_source', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['destination_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['origin_port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vessel_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vessel_class_id', sa.Integer(), nullable=True),
    sa.Column('imo_number', sa.String(length=16), nullable=True),
    sa.Column('dwt', sa.Float(), nullable=True),
    sa.Column('cargo_capacity', sa.Float(), nullable=True),
    sa.Column('draft', sa.Float(), nullable=True),
    sa.Column('loa', sa.Float(), nullable=True),
    sa.Column('beam', sa.Float(), nullable=True),
    sa.Column('speed_laden', sa.Float(), nullable=True),
    sa.Column('speed_ballast', sa.Float(), nullable=True),
    sa.Column('consumption_laden', sa.Float(), nullable=True),
    sa.Column('consumption_ballast', sa.Float(), nullable=True),
    sa.Column('employment_control', sa.Enum('CONTROLLED', 'NOT_CONTROLLED', 'UNKNOWN', name='employmentcontrolenum'), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['vessel_class_id'], ['vessel_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imo_number')
    )
    op.create_table('candidate_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vessel_profile_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('cargo_parcel_id', sa.Integer(), nullable=True),
    sa.Column('contract_strategy', sa.Enum('SPOT', 'SHORT_TERM', 'MEDIUM_TERM', 'MULTI_VOYAGE', name='contractstrategyenum'), nullable=True),
    sa.Column('estimated_freight_cost', sa.Float(), nullable=True),
    sa.Column('estimated_bunker_cost', sa.Float(), nullable=True),
    sa.Column('estimated_port_cost', sa.Float(), nullable=True),
    sa.Column('estimated_total_cost', sa.Float(), nullable=True),
    sa.Column('arrival_date', sa.DateTime(), nullable=True),
    sa.Column('max_voyages', sa.Integer(), nullable=True),
    sa.Column('eligibility', sa.Boolean(), nullable=True),
    sa.Column('eligibility_reason', sa.Text(), nullable=True),
    sa.Column('data_kind', sa.Enum('OBSERVED', 'PROXY', 'DERIVED', 'SYNTHETIC', 'MODEL_PREDICTION', name='datakindenum'), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cargo_parcel_id'], ['cargo_parcels.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['vessel_profile_id'], ['vessel_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('optimization_run_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=True),
    sa.Column('runtime_mode', sa.Enum('LIVE', 'OFFLINE_DEMO', name='runtimemodeenum'), nullable=False),
    sa.Column('data_context_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vessel_availability_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vessel_profile_id', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('location_port_id', sa.Integer(), nullable=True),
    sa.Column('location_description', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('data_kind', sa.Enum('OBSERVED', 'PROXY', 'DERIVED', 'SYNTHETIC', 'MODEL_PREDICTION', name='datakindenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['location_port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['vessel_profile_id'], ['vessel_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vessel_commitments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vessel_profile_id', sa.Integer(), nullable=False),
    sa.Column('commitment_start', sa.DateTime(), nullable=False),
    sa.Column('commitment_end', sa.DateTime(), nullable=True),
    sa.Column('route_description', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('is_immutable', sa.Boolean(), nullable=True),
    sa.Column('employment_control_ref', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['vessel_profile_id'], ['vessel_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('runtime_mode', sa.Enum('LIVE', 'OFFLINE_DEMO', name='runtimemodeenum'), nullable=True),
    sa.Column('mode_session_id', sa.String(length=64), nullable=True),
    sa.Column('data_context_id', sa.String(length=64), nullable=True),
    sa.Column('source_manifest_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idle_employment_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vessel_profile_id', sa.Integer(), nullable=False),
    sa.Column('availability_event_id', sa.Integer(), nullable=True),
    sa.Column('commitment_id', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('idle_days', sa.Float(), nullable=True),
    sa.Column('employment_control', sa.Enum('CONTROLLED', 'NOT_CONTROLLED', 'UNKNOWN', name='employmentcontrolenum'), nullable=True),
    sa.Column('is_actionable', sa.Boolean(), nullable=True),
    sa.Column('selected_action', sa.Enum('WAIT', 'REPOSITION', 'ALTERNATIVE_EMPLOYMENT', name='idleactionenum'), nullable=True),
    sa.Column('runtime_mode', sa.Enum('LIVE', 'OFFLINE_DEMO', name='runtimemodeenum'), nullable=False),
    sa.Column('data_context_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['availability_event_id'], ['vessel_availability_events.id'], ),
    sa.ForeignKeyConstraint(['commitment_id'], ['vessel_commitments.id'], ),
    sa.ForeignKeyConstraint(['vessel_profile_id'], ['vessel_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idle_action_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('WAIT', 'REPOSITION', 'ALTERNATIVE_EMPLOYMENT', name='idleactionenum'), nullable=False),
    sa.Column('is_feasible', sa.Boolean(), nullable=True),
    sa.Column('feasibility_reason', sa.Text(), nullable=True),
    sa.Column('idle_cost', sa.Float(), nullable=True),
    sa.Column('reposition_cost', sa.Float(), nullable=True),
    sa.Column('bunker_cost', sa.Float(), nullable=True),
    sa.Column('port_cost', sa.Float(), nullable=True),
    sa.Column('expected_contribution', sa.Float(), nullable=True),
    sa.Column('total_expected_cost', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('reason_codes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['idle_employment_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idle_action_evaluations')
    op.drop_table('idle_employment_evaluations')
    op.drop_table('audit_events')
    op.drop_table('vessel_commitments')
    op.drop_table('vessel_availability_events')
    op.drop_table('recommendations')
    op.drop_table('candidate_services')
    op.drop_table('vessel_profiles')
    op.drop_table('routes')
    op.drop_table('port_constraints')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_market_observations_series_id'), table_name='market_observations')
    op.drop_index('ix_market_obs_series_observed', table_name='market_observations')
    op.drop_index('ix_market_obs_series_available', table_name='market_observations')
    op.drop_table('market_observations')
    op.drop_table('forecasts')
    op.drop_table('cargo_parcels')
    op.drop_table('vessel_classes')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_runtime_mode_events_mode_session_id'), table_name='runtime_mode_events')
    op.drop_table('runtime_mode_events')
    op.drop_table('ports')
    op.drop_index(op.f('ix_offline_packages_package_id'), table_name='offline_packages')
    op.drop_table('offline_packages')
    op.drop_table('forecast_runs')
    op.drop_table('data_sources')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
